image: pawan793/appium_with_python

pipelines:
  default:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pytest -v -m  Login_Logout --cap-file=SiminvestAppQa\src\cap_files\lt_cap_file.py --lt --junitxml=test-reports/results.xml