image: pawan793/appium_with_python
pipelines:
  default:
      - step:
          name: Test -1 HomePage
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Homepage -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      # - step:
      #     name: Test -2 ReasechPage
      #     caches:
      #       - pip
      #     script:
      #       - apt-get clean
      #       - apt-get update
      #       - apt-get install --fix-missing
      #       - apt-get install -y unzip git
      #       - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      #       - pytest -v -m Research -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
      #       - python3 post_test_report.py
      #       - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
      #       - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
      #     artifacts:
      #       - allure-results/**
      - step:
          name: Test -3 UserProfile
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m userProfile -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -4 LoginLogout
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Login_Logout -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -5 watchlist
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m watchlist -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -6 Mover Page
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m MoverPage -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -7 SDP Page
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m SDP -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -8 Transaction Page
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Transaction -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -9 FastOrder
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m fastOrder -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -10 SaldoRdn
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m saldoRdn -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -11 BuyProcess
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m BuyProcess -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -12 SellProcess
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m SellProcess -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -13 AmendProcess
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Amend -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -14 Withdraw Process
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Cancel -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -15 Portfolio
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Portfolio -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -16 SectorPage
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m SectorPage -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -17 SearchSuggestion
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m SearchSuggestion -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -18 Index Page
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m index -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -19 Event Page
          caches:
            - pip
          script:
            - apt-get clean
            - apt-get update
            - apt-get install --fix-missing
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Event -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - python3 post_report_url.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      #- step:
       #   name: Test -20 Gamification
        #  caches:
         #   - pip
          #script:
           # - apt-get clean
            #- apt-get update
            #- apt-get install --fix-missing
            #- apt-get install -y unzip git
            #- if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            #- pytest -v -m Gamification -n 1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            #- python3 post_test_report.py
            #- python3 post_report_url.py
            #- git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            #- cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          #artifacts:
            #- allure-results/**

      - step:
          name: Report
          image: frankescobar/allure-docker-service
          script:
            - allure generate allure-results/
          artifacts:
            - allure-report/**

      - step:
          name: UploadReport
          image: python:3.9
          script:
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - git config --global user.name bitbucket-pipelines
            - git config --global user.email commits-noreply@bitbucket.org
            - rm -rf smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/
            - cp -r allure-report/ smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/
            - cd smssekuritas.bitbucket.io
            - git add .
            - git commit -m "Report Updated"
            - git push
