image: appium/appium

pipelines:
  default:
      - step:
          name: Test
          caches:
            - pip
          script:
            - apt-get update -y
            - apt-get install python3.9 -y
            - apt-get install python-pip -y
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pytest -v --cap-file=SiminvestAppQa\src\cap_files\lt_cap_file.py --lt --junitxml=test-reports/results.xml
