#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: appium/appium

pipelines:
  default:
      - step:
          name: Test
          caches:
            - pip
          script:
            - apt-get install python3.9
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
