image: pawan793/python_with_appium

pipelines:
  default:
      - step:
          name: Test
          script:
            - pip install --upgrade setuptools
            - pip install --upgrade pip
            - pip install pytest
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pytest -v -m  Login_Logout --cap-file=SiminvestAppQa\src\cap_files\lt_cap_file.py --lt --junitxml=test-reports/results.xml