#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: appium/appium

pipelines:
  default:
      - step:
          name: Test
          caches:
            - pip
          script:
            - apt-get update -y
            - apt-get install python3.10 -y
            - apt-get install python3-pip -y
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            #- pytest -v --cap-file=SiminvestAppQa/src/cap_files/bs_android_cap.py --bs --junitxml=test-reports/results.xml
