image: pawan793/appium_with_python
pipelines:
  default:
      - step:
          name: Test -1 HomePage
          caches:
            - pip
          script:
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Homepage_1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Test -2 ReasechPage
          caches:
            - pip
          script:
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Research_1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -3 UserProfile
          caches:
            - pip
          script:
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m userProfile_1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -4 LoginLogout
          caches:
            - pip
          script:
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m Login_Logout_1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**
      - step:
          name: Test -5 watchlist
          caches:
            - pip
          script:
            - apt-get install -y unzip git
            - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            - pytest -v -m watchlist_1 --cap-file=SiminvestAppQa/src/cap_files/lt_cap_file.py --lt --junitxml=test-reports/results.xml  --alluredir=allure-results  > test.log|| true
            - python3 post_test_report.py
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - cp -r smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/history/ allure-results/history/
          artifacts:
            - allure-results/**

      - step:
          name: Report
          image: frankescobar/allure-docker-service
          script:
            - allure generate allure-results/
          artifacts:
            - allure-report/**

      - step:
          name: UploadReport
          image: python:3.9
          script:
            - git clone git@bitbucket.org:smssekuritas/smssekuritas.bitbucket.io.git
            - git config --global user.name bitbucket-pipelines
            - git config --global user.email commits-noreply@bitbucket.org
            - rm -rf smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/
            - cp -r allure-report/ smssekuritas.bitbucket.io/siminvest-app-qa/allure-report/
            - cd smssekuritas.bitbucket.io
            - git add .
            - git commit -m "Report Updated"
            - git push